sudo: false
language: ruby

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3

branches:
  only:
  - master

script: bundle exec rake ci
